CREATE TABLE "mytable" (
  "create or replace procedure CreateNewUser(A_id in int" text,
  "name in varchar2" text,
  "password in varchar2" text,
  "phone in int" text,
  "username in varchar2 default null" text,
  "age in int default null" text,
  "Door in number default null" text,
  "street in varchar2 default null" text,
  "city in varchar2 default null" text,
  "state in varchar2 default null" text,
  "pin in int default null) as" text
);

INSERT INTO "mytable" ("create or replace procedure CreateNewUser(A_id in int","name in varchar2","password in varchar2","phone in int","username in varchar2 default null","age in int default null","Door in number default null","street in varchar2 default null","city in varchar2 default null","state in varchar2 default null","pin in int default null) as")
VALUES
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('insert into users values(A_id','name','age','username','password','Door','street','city','state','pin);',NULL),
('insert into contact values(A_id','phone);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''User created'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('set server output on;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('exec CreateNewUser(0000229','''rocky''','''cool@123''','982749274928','''COOLGUY''','50','111','''path''','''chennai''','''tamilnadu''','782020);'),
('create or replace procedure InsertUserPhone(A_id in int','phone in int) as',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('insert into contact values(A_id','phone);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''Phone number added'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('create or replace procedure InsertPropertyRecord(P_id in int','ownerId in int','Total_area in int','Plinth_area in int','address in varchar2','locality in varchar2','Rentpmonth in int','yrOfConst in int','AvailableFrom in varchar2 default null','AvailableTill in varchar2 default null','noOfBedrooms in int default null'),
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('insert into property values(P_id','ownerId','tenantId','yrOfConst','Total_area','Plinth_area','AvailableFrom','AvailableTill','Rentpmonth','floors','annualhike'),
('dbms_output.put_line('' Property added'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('exec InsertPropertyRecord(10','0000201','2000','2200','''PAnaji''','''goa''','39000','2002','Null','Null','Null'),
('create or replace procedure GetPropertyRecords(ownerid in int) as',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P_id int;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Total_area int;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Plinth_area int;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('AvailableFrom varchar(20);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('AvailableTill varchar2(20);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('address varchar2(20);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('locality varchar2(20);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('yrOfConst int;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('annualhike number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('cursor props is',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('select P_id','Total_area','Plinth_area','AvailableFrom','AvailableTill','address','locality','yrOfConst','annualhike from property where ownerId = ownerid;',NULL,NULL),
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := 0;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('open props;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''::::Owner with id: ''||ownerid||'' has the following properties::::'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('loop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('fetch props into P_id','Total_area','Plinth_area','AvailableFrom','AvailableTill','address','locality','yrOfConst','annualhike;',NULL,NULL),
('exit when props%notfound;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := p + 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Property ''||p);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Property Id: ''||P_id);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Total Area: ''||Total_area);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Plinth Area: ''||Plinth_area);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Available from: ''||AvailableFrom);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Address: ''||address);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Locality: ''||locality);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Construction Year: ''||yrOfConst);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Annual Hike: ''||annualhike);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if AvailableTill is NULL then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Property available indefinitely'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('else',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Property available till: ''||AvailableTill);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''-'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end loop;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('close props;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if p = 0 then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' No properties registered yet'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Above information is subject to change'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('declare',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('2  ownerid int;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3  begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('4  ownerid :=0000001;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('5  GetPropertyRecords(ownerid);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('6  end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('7  /',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('create or replace procedure GetTenantDetails(P_id in int) as',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('ph number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('id number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('nm varchar2(20);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('sdate date;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('rpm number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('yhike number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('comm number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('cursor tens is',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('select tid','name','phone','start_date','rentpm','yearly_hike','commission from (rent join users on tid = aid) join user_phone on userid = tid where pid = propid and end_date is NULL;',NULL,NULL,NULL,NULL),
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := 0;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('open tens;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('loop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('fetch tens into id','nm','ph','sdate','rpm','yhike','comm;',NULL,NULL,NULL,NULL),
('exit when tens%notfound;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := p + 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if p = 1 then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Occupying Tenant id: ''||id);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Tenant Name: ''||nm);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Started on: ''||sdate);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Current Rent per Month: ''||rpm);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Yearly Rate Hike: ''||yhike);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if comm is NULL then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' No commission involved'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('else',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Commission: ''||comm);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Phone number: ''||ph);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('else',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Phone number: ''||ph);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end loop;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('close tens;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if p = 0 then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Either this property does not exists or it currently has no tenants'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('create or replace procedure GetRentHistory(P_id in int) as',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('id number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('sdate date;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('edate date;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('trent number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('cursor tens is',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('select tid','start_date','end_date','total_rent from rent_history natural join rent where pid = propid;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := 0;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('open tens;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''::::Property with id: ''||P_id||'' has had the following tenants::::'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('loop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('fetch tens into id','sdate','edate','trent;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('exit when tens%notfound;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := p + 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Tenant ''||p);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Tenant id: ''||T_id);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Occupied the Property from: ''||sdate);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if edate is NULL then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' till today','and onwards'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('else',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Till: ''||edate);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Net Rent amount: ''||trent);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''-'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end loop;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if p = 0 then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Either this property does not exist or no tenants have finished their tenure on it yet'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('close tens;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('create or replace procedure SearchPropertyForRent(locality in varchar2) as',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P_id number;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('cursor props is',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('select pid from property where locality = loc;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('begin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := 0;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''::::Locality/Street: ''||loc||'' has the following properties::::'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('open props;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('loop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('fetch props into id;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('exit when props%notfound;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('p := p + 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line('' Property ''||p);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GetPropertyRecordwithPID(id);',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''-'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end loop;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('close props;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('if p = 0 then',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dbms_output.put_line(''No properties found'');',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end if;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('end;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
